# Generated by Django 3.2.6 on 2021-11-11 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('website', models.CharField(blank=True, max_length=200)),
                ('region', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='StockQuoteHist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('update_at', models.DateTimeField(null=True)),
                ('change_percent', models.FloatField()),
                ('fk_ativo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stock_quotes.stockquote')),
            ],
        ),
    ]
